# Generated by Django 4.1 on 2023-04-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subscription_meta_alter_conector_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
