# Generated by Django 4.2.2 on 2023-06-24 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subscriptiongroup_subscription_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='conector',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conector',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
